// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type StorageAttachment struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	RecordType string    `json:"record_type"`
	RecordID   string    `json:"record_id"`
	BlobID     uuid.UUID `json:"blob_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type StorageBlob struct {
	ID          uuid.UUID    `json:"id"`
	Key         string       `json:"key"`
	Filename    string       `json:"filename"`
	ContentType *string      `json:"content_type"`
	Metadata    pgtype.JSONB `json:"metadata"`
	ByteSize    int64        `json:"byte_size"`
	Checksum    *string      `json:"checksum"`
	CreatedAt   time.Time    `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Bio       *string   `json:"bio"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
