// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Post struct {
	ID          string     `json:"id"`
	UserID      string     `json:"user_id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Abstract    *string    `json:"abstract"`
	Body        string     `json:"body"`
	Published   bool       `json:"published"`
	PublishDate *time.Time `json:"publish_date"`
	Location    *string    `json:"location"`
	Lat         *float64   `json:"lat"`
	Lon         *float64   `json:"lon"`
	Locale      *string    `json:"locale"`
	Tags        []string   `json:"tags"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type StorageAttachment struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	RecordType string    `json:"record_type"`
	RecordID   string    `json:"record_id"`
	BlobID     uuid.UUID `json:"blob_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type StorageBlob struct {
	ID          uuid.UUID    `json:"id"`
	Key         string       `json:"key"`
	Filename    string       `json:"filename"`
	ContentType *string      `json:"content_type"`
	Metadata    pgtype.JSONB `json:"metadata"`
	ByteSize    int64        `json:"byte_size"`
	Checksum    *string      `json:"checksum"`
	CreatedAt   time.Time    `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Bio       *string   `json:"bio"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
