// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"
	"time"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags, created_at, updated_at
`

type CreatePostParams struct {
	ID          string     `json:"id"`
	UserID      string     `json:"user_id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Abstract    *string    `json:"abstract"`
	Body        string     `json:"body"`
	Published   bool       `json:"published"`
	PublishDate *time.Time `json:"publish_date"`
	Location    *string    `json:"location"`
	Lat         *float64   `json:"lat"`
	Lon         *float64   `json:"lon"`
	Locale      *string    `json:"locale"`
	Tags        []string   `json:"tags"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (*Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.Abstract,
		arg.Body,
		arg.Published,
		arg.PublishDate,
		arg.Location,
		arg.Lat,
		arg.Lon,
		arg.Locale,
		arg.Tags,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Abstract,
		&i.Body,
		&i.Published,
		&i.PublishDate,
		&i.Location,
		&i.Lat,
		&i.Lon,
		&i.Locale,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags, created_at, updated_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id string) (*Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Abstract,
		&i.Body,
		&i.Published,
		&i.PublishDate,
		&i.Location,
		&i.Lat,
		&i.Lon,
		&i.Locale,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags, created_at, updated_at FROM posts
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (*Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Abstract,
		&i.Body,
		&i.Published,
		&i.PublishDate,
		&i.Location,
		&i.Lat,
		&i.Lon,
		&i.Locale,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags, created_at, updated_at FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]*Post, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Abstract,
			&i.Body,
			&i.Published,
			&i.PublishDate,
			&i.Location,
			&i.Lat,
			&i.Lon,
			&i.Locale,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUserID = `-- name: ListPostsByUserID :many
SELECT id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags, created_at, updated_at FROM posts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]*Post, error) {
	rows, err := q.db.Query(ctx, listPostsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Abstract,
			&i.Body,
			&i.Published,
			&i.PublishDate,
			&i.Location,
			&i.Lat,
			&i.Lon,
			&i.Locale,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    title = COALESCE($1, title),
    slug = COALESCE($2, slug),
    abstract = COALESCE($3, abstract),
    body = COALESCE($4, body),
    published = COALESCE($5, published),
    publish_date = COALESCE($6, publish_date),
    location = COALESCE($7, location),
    lat = COALESCE($8, lat),
    lon = COALESCE($9, lon),
    locale = COALESCE($10, locale),
    tags = COALESCE($11, tags),
    updated_at = NOW()
WHERE id = $12
RETURNING id, user_id, title, slug, abstract, body, published, publish_date, location, lat, lon, locale, tags, created_at, updated_at
`

type UpdatePostParams struct {
	Title       *string    `json:"title"`
	Slug        *string    `json:"slug"`
	Abstract    *string    `json:"abstract"`
	Body        *string    `json:"body"`
	Published   *bool      `json:"published"`
	PublishDate *time.Time `json:"publish_date"`
	Location    *string    `json:"location"`
	Lat         *float64   `json:"lat"`
	Lon         *float64   `json:"lon"`
	Locale      *string    `json:"locale"`
	Tags        []string   `json:"tags"`
	ID          string     `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (*Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Slug,
		arg.Abstract,
		arg.Body,
		arg.Published,
		arg.PublishDate,
		arg.Location,
		arg.Lat,
		arg.Lon,
		arg.Locale,
		arg.Tags,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Abstract,
		&i.Body,
		&i.Published,
		&i.PublishDate,
		&i.Location,
		&i.Lat,
		&i.Lon,
		&i.Locale,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
