// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO storage_attachments (name, record_type, record_id, blob_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (record_type, record_id, name) 
DO UPDATE SET blob_id = EXCLUDED.blob_id, created_at = CURRENT_TIMESTAMP
RETURNING id, name, record_type, record_id, blob_id, created_at
`

type CreateAttachmentParams struct {
	Name       string    `json:"name"`
	RecordType string    `json:"record_type"`
	RecordID   string    `json:"record_id"`
	BlobID     uuid.UUID `json:"blob_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (*StorageAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.Name,
		arg.RecordType,
		arg.RecordID,
		arg.BlobID,
	)
	var i StorageAttachment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RecordType,
		&i.RecordID,
		&i.BlobID,
		&i.CreatedAt,
	)
	return &i, err
}

const createBlob = `-- name: CreateBlob :one
INSERT INTO storage_blobs (id, key, filename, content_type, byte_size, checksum, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key, filename, content_type, metadata, byte_size, checksum, created_at
`

type CreateBlobParams struct {
	ID          uuid.UUID    `json:"id"`
	Key         string       `json:"key"`
	Filename    string       `json:"filename"`
	ContentType *string      `json:"content_type"`
	ByteSize    int64        `json:"byte_size"`
	Checksum    *string      `json:"checksum"`
	Metadata    pgtype.JSONB `json:"metadata"`
}

func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) (*StorageBlob, error) {
	row := q.db.QueryRow(ctx, createBlob,
		arg.ID,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Checksum,
		arg.Metadata,
	)
	var i StorageBlob
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.Metadata,
		&i.ByteSize,
		&i.Checksum,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM storage_attachments
WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const deleteBlob = `-- name: DeleteBlob :exec
DELETE FROM storage_blobs
WHERE id = $1
`

func (q *Queries) DeleteBlob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlob, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT 
    a.id, a.name, a.record_type, a.record_id, a.blob_id, a.created_at,
    b.key,
    b.filename,
    b.content_type,
    b.byte_size
FROM storage_attachments a
JOIN storage_blobs b ON a.blob_id = b.id
WHERE a.record_type = $1 AND a.record_id = $2 AND a.name = $3
LIMIT 1
`

type GetAttachmentParams struct {
	RecordType string `json:"record_type"`
	RecordID   string `json:"record_id"`
	Name       string `json:"name"`
}

type GetAttachmentRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	RecordType  string    `json:"record_type"`
	RecordID    string    `json:"record_id"`
	BlobID      uuid.UUID `json:"blob_id"`
	CreatedAt   time.Time `json:"created_at"`
	Key         string    `json:"key"`
	Filename    string    `json:"filename"`
	ContentType *string   `json:"content_type"`
	ByteSize    int64     `json:"byte_size"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (*GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.RecordType, arg.RecordID, arg.Name)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RecordType,
		&i.RecordID,
		&i.BlobID,
		&i.CreatedAt,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
	)
	return &i, err
}

const getAttachmentByRecord = `-- name: GetAttachmentByRecord :one
SELECT id, blob_id, record_type, record_id, name
FROM storage_attachments
WHERE record_type = $1 AND record_id = $2 AND name = $3
LIMIT 1
`

type GetAttachmentByRecordParams struct {
	RecordType string `json:"record_type"`
	RecordID   string `json:"record_id"`
	Name       string `json:"name"`
}

type GetAttachmentByRecordRow struct {
	ID         uuid.UUID `json:"id"`
	BlobID     uuid.UUID `json:"blob_id"`
	RecordType string    `json:"record_type"`
	RecordID   string    `json:"record_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetAttachmentByRecord(ctx context.Context, arg GetAttachmentByRecordParams) (*GetAttachmentByRecordRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentByRecord, arg.RecordType, arg.RecordID, arg.Name)
	var i GetAttachmentByRecordRow
	err := row.Scan(
		&i.ID,
		&i.BlobID,
		&i.RecordType,
		&i.RecordID,
		&i.Name,
	)
	return &i, err
}

const getBlob = `-- name: GetBlob :one
SELECT id, key, filename, content_type, metadata, byte_size, checksum, created_at FROM storage_blobs
WHERE id = $1
`

func (q *Queries) GetBlob(ctx context.Context, id uuid.UUID) (*StorageBlob, error) {
	row := q.db.QueryRow(ctx, getBlob, id)
	var i StorageBlob
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.Metadata,
		&i.ByteSize,
		&i.Checksum,
		&i.CreatedAt,
	)
	return &i, err
}
